// Gerado a partir dos Assets do app (cores das 12 paletas).
export type PaletteColor = { hex: string; name: string; keywords: string[] };

export const PALETTES: Record<string, PaletteColor[]> = {
  springClear: [
    { hex: "#E95283", name: "coral", keywords: ["coral", "pink", "orange"] },
    { hex: "#FE3E42", name: "red", keywords: ["red"] },
    { hex: "#ED7F20", name: "orange", keywords: ["orange"] },
    { hex: "#FCC531", name: "yellow", keywords: ["yellow"] },
    { hex: "#22A641", name: "green", keywords: ["green"] },
    { hex: "#70E9D9", name: "light blue", keywords: ["blue"] },
    { hex: "#3D55B2", name: "blue", keywords: ["blue"] },
  ],
  springWarn: [
    { hex: "#EA6E77", name: "coral", keywords: ["coral", "pink", "orange"] },
    { hex: "#F8926C", name: "coral", keywords: ["coral", "pink", "orange"] },
    { hex: "#FAB641", name: "yellow", keywords: ["yellow"] },
    { hex: "#93AA46", name: "camel", keywords: ["camel", "tan", "beige"] },
    { hex: "#319A48", name: "green", keywords: ["green"] },
    { hex: "#2EA79D", name: "blue", keywords: ["blue"] },
    { hex: "#1178BA", name: "blue", keywords: ["blue"] },
  ],
  springLight: [
    { hex: "#F7DB92", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#FEB294", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#FBB8D0", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#FEA5A4", name: "pink", keywords: ["pink"] },
    { hex: "#C8EFBB", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#94D6D5", name: "light blue", keywords: ["blue"] },
    { hex: "#BCE6F7", name: "light blue", keywords: ["blue"] },
  ],
  summerSoft: [
    { hex: "#F1DFAB", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#E2ABB7", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#D783AB", name: "pink", keywords: ["pink"] },
    { hex: "#B581A6", name: "pink", keywords: ["pink"] },
    { hex: "#84BBAE", name: "light blue", keywords: ["blue"] },
    { hex: "#8BAABE", name: "light blue", keywords: ["blue"] },
    { hex: "#436993", name: "blue", keywords: ["blue"] },
  ],
  summerCool: [
    { hex: "#C7326C", name: "terracotta", keywords: ["terracotta", "rust", "orange"] },
    { hex: "#F384D8", name: "pink", keywords: ["pink"] },
    { hex: "#BE8EC6", name: "lavender", keywords: ["lavender", "lilac", "purple"] },
    { hex: "#6C8FCA", name: "light blue", keywords: ["blue"] },
    { hex: "#49A6EC", name: "light blue", keywords: ["blue"] },
    { hex: "#3B8A84", name: "green", keywords: ["green"] },
    { hex: "#737D90", name: "gray", keywords: ["gray", "grey"] },
  ],
  summerLight: [
    { hex: "#FFFAAD", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#FBCBD8", name: "white", keywords: ["white"] },
    { hex: "#F9B5E5", name: "lavender", keywords: ["lavender", "lilac", "purple"] },
    { hex: "#DEC6F5", name: "lavender", keywords: ["lavender", "lilac", "purple"] },
    { hex: "#B4B6D8", name: "lavender", keywords: ["lavender", "lilac", "purple"] },
    { hex: "#92BAF7", name: "light blue", keywords: ["blue"] },
    { hex: "#9ED4DA", name: "light blue", keywords: ["blue"] },
  ],
  autumnSoft: [
    { hex: "#E59691", name: "pink", keywords: ["pink"] },
    { hex: "#E8B1B8", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#DDC48C", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#BDB7AC", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#A6B99C", name: "beige", keywords: ["beige", "cream", "nude"] },
    { hex: "#A9CCC4", name: "light blue", keywords: ["blue"] },
    { hex: "#75ADCC", name: "light blue", keywords: ["blue"] },
  ],
  autumnWarn: [
    { hex: "#F8A947", name: "yellow", keywords: ["yellow"] },
    { hex: "#F08142", name: "orange", keywords: ["orange"] },
    { hex: "#EC7B6E", name: "coral", keywords: ["coral", "pink", "orange"] },
    { hex: "#C63822", name: "red", keywords: ["red"] },
    { hex: "#8E543A", name: "brown", keywords: ["brown", "chocolate"] },
    { hex: "#8A8C3D", name: "olive", keywords: ["olive", "khaki", "green"] },
    { hex: "#6A836B", name: "gray", keywords: ["gray", "grey"] },
  ],
  autumnDeep: [
    { hex: "#CF8329", name: "orange", keywords: ["orange"] },
    { hex: "#BE6C56", name: "terracotta", keywords: ["terracotta", "rust", "orange"] },
    { hex: "#971B21", name: "burgundy", keywords: ["burgundy", "maroon", "wine", "red"] },
    { hex: "#6D3B39", name: "brown", keywords: ["brown", "chocolate"] },
    { hex: "#7C7240", name: "olive", keywords: ["olive", "khaki", "green"] },
    { hex: "#1C5546", name: "teal", keywords: ["teal", "turquoise", "green"] },
    { hex: "#064569", name: "teal", keywords: ["teal", "turquoise", "green"] },
  ],
  winterClear: [
    { hex: "#CB2052", name: "red", keywords: ["red"] },
    { hex: "#F488B6", name: "pink", keywords: ["pink"] },
    { hex: "#28B97E", name: "green", keywords: ["green"] },
    { hex: "#53BFD3", name: "light blue", keywords: ["blue"] },
    { hex: "#1F63AC", name: "blue", keywords: ["blue"] },
    { hex: "#7951A5", name: "purple", keywords: ["purple", "violet"] },
    { hex: "#9C9E9B", name: "gray", keywords: ["gray", "grey"] },
  ],
  winterCool: [
    { hex: "#F54A8B", name: "coral", keywords: ["coral", "pink", "orange"] },
    { hex: "#FA65C9", name: "pink", keywords: ["pink"] },
    { hex: "#A56ACF", name: "lavender", keywords: ["lavender", "lilac", "purple"] },
    { hex: "#4168D7", name: "blue", keywords: ["blue"] },
    { hex: "#02CCFE", name: "blue", keywords: ["blue"] },
    { hex: "#42BA8C", name: "gray", keywords: ["gray", "grey"] },
    { hex: "#F8E59A", name: "beige", keywords: ["beige", "cream", "nude"] },
  ],
  winterDeep: [
    { hex: "#CC3184", name: "terracotta", keywords: ["terracotta", "rust", "orange"] },
    { hex: "#BF2144", name: "red", keywords: ["red"] },
    { hex: "#952852", name: "burgundy", keywords: ["burgundy", "maroon", "wine", "red"] },
    { hex: "#612878", name: "purple", keywords: ["purple", "violet"] },
    { hex: "#132284", name: "navy", keywords: ["navy", "blue"] },
    { hex: "#1A615C", name: "teal", keywords: ["teal", "turquoise", "green"] },
    { hex: "#37435B", name: "teal", keywords: ["teal", "turquoise", "green"] },
  ],
};
